# Generated by Django 6.0.7 on 2026-08-09 07:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDiscountConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Default 2% discount for account holders', max_digits=5)),
                ('minimum_order_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('maximum_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('eligible_after_orders', models.PositiveIntegerField(default=0, help_text='Minimum orders required before discount applies')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'account_discount_config',
            },
        ),
    ]
