# Generated by Django 6.0.7 on 2026-08-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ga4_enabled', models.BooleanField(default=False)),
                ('ga4_measurement_id', models.CharField(blank=True, max_length=50)),
                ('gtm_enabled', models.BooleanField(default=False)),
                ('gtm_container_id', models.CharField(blank=True, max_length=50)),
                ('meta_pixel_enabled', models.BooleanField(default=False)),
                ('meta_pixel_id', models.CharField(blank=True, max_length=50)),
                ('custom_head_scripts', models.TextField(blank=True, help_text='Custom HTML/JS injected in <head>')),
                ('custom_body_scripts', models.TextField(blank=True, help_text='Custom HTML/JS injected after <body>')),
            ],
            options={
                'db_table': 'tracking_settings',
            },
        ),
    ]
