# Generated by Django 6.0.7 on 2026-08-09 07:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbandonedCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('items_snapshot', models.JSONField(default=list, help_text='Snapshot of cart items at abandonment')),
                ('total_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('abandoned_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recovered', models.BooleanField(db_index=True, default=False)),
                ('recovered_at', models.DateTimeField(blank=True, null=True)),
                ('campaign_sent', models.BooleanField(default=False)),
                ('campaign_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'abandoned_carts',
                'ordering': ['-abandoned_at'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'carts',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'cart_items',
            },
        ),
    ]
