# Generated by Django 6.0.7 on 2026-08-09 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0001_initial'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=500)),
                ('link_url', models.CharField(blank=True, max_length=300)),
                ('link_text', models.CharField(blank=True, max_length=100)),
                ('background_color', models.CharField(default='#1a1a2e', max_length=20)),
                ('text_color', models.CharField(default='#ffffff', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('dismissible', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'announcement_bars',
            },
        ),
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section_type', models.CharField(choices=[('hero', 'Hero Carousel'), ('banner', 'Banner'), ('category_grid', 'Category Grid'), ('product_grid', 'Product Grid'), ('flash_sale', 'Flash Sale'), ('deals', 'Deals'), ('offers', 'Offers'), ('featured_products', 'Featured Products'), ('trending_products', 'Trending Products'), ('best_sellers', 'Best Sellers'), ('new_arrivals', 'New Arrivals'), ('recently_viewed', 'Recently Viewed'), ('brands', 'Brand Showcase'), ('testimonials', 'Testimonials'), ('video_gallery', 'Video Gallery'), ('trust_features', 'Trust Features'), ('custom_html', 'Custom HTML'), ('newsletter', 'Newsletter Signup'), ('countdown', 'Countdown Timer'), ('promotion', 'Promotion Section')], max_length=30)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField(blank=True, help_text='For custom_html type')),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage/')),
                ('link_url', models.CharField(blank=True, max_length=300)),
                ('link_text', models.CharField(blank=True, max_length=100)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('max_items', models.PositiveIntegerField(default=12, help_text='Max products/items to show')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Extra configuration (columns, colors, etc.)')),
                ('featured_categories', models.ManyToManyField(blank=True, related_name='homepage_sections', to='categories.category')),
                ('featured_products', models.ManyToManyField(blank=True, related_name='homepage_sections', to='products.product')),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_sections', to='promotions.promotion')),
            ],
            options={
                'db_table': 'homepage_sections',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(upload_to='hero/')),
                ('mobile_image', models.ImageField(blank=True, null=True, upload_to='hero/mobile/')),
                ('cta_text', models.CharField(blank=True, max_length=100)),
                ('cta_url', models.CharField(blank=True, max_length=300)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_slides', to='homepage.homepagesection')),
            ],
            options={
                'db_table': 'hero_slides',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='banners/')),
                ('mobile_image', models.ImageField(blank=True, null=True, upload_to='banners/mobile/')),
                ('link_url', models.CharField(blank=True, max_length=300)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='homepage.homepagesection')),
            ],
            options={
                'db_table': 'banners',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('customer_location', models.CharField(blank=True, max_length=100)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('text', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='homepage.homepagesection')),
            ],
            options={
                'db_table': 'testimonials',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='TrustFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icon', models.CharField(blank=True, help_text='Icon name or SVG', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_features', to='homepage.homepagesection')),
            ],
            options={
                'db_table': 'trust_features',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='VideoGalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('video_url', models.URLField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='videos/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_items', to='homepage.homepagesection')),
            ],
            options={
                'db_table': 'video_gallery_items',
                'ordering': ['sort_order'],
            },
        ),
    ]
