# Generated by Django 6.0.7 on 2026-08-17 11:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='chargeable_weight_grams',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_charge_reason',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='is_single_product_free_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='total_physical_weight_grams',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='delivery_charge_applicable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='density_g_per_ml',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=6),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='free_delivery_when_alone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='measurement_type',
            field=models.CharField(default='weight', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='measurement_unit',
            field=models.CharField(default='g', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='measurement_value',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total_weight_grams',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit_weight_grams',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12),
        ),
    ]
