# Generated by Django 6.0.7 on 2026-08-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_chargeable_weight_grams_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_tier_max_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_tier_min_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_tier_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
