# Generated by Django 6.0.7 on 2026-08-09 07:10

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('promotion_type', models.CharField(choices=[('flash_sale', 'Flash Sale'), ('percentage', 'Percentage Discount'), ('fixed', 'Fixed Discount'), ('bogo', 'Buy One Get One'), ('bundle', 'Bundle Discount'), ('category', 'Category Offer'), ('product', 'Product Offer'), ('new_customer', 'New Customer Offer'), ('account', 'Account Customer Offer'), ('seasonal', 'Seasonal Offer'), ('limited_time', 'Limited Time Offer')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], default='percentage', max_length=20)),
                ('minimum_quantity', models.PositiveIntegerField(default=1)),
                ('buy_quantity', models.PositiveIntegerField(default=1, help_text='BOGO: buy X')),
                ('get_quantity', models.PositiveIntegerField(default=1, help_text='BOGO: get Y free')),
                ('start_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher = applied first when conflicts')),
                ('stackable', models.BooleanField(default=False, help_text='Can stack with coupons/other promotions')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='promotions/')),
                ('badge_text', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'promotions',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='categories.category')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='promotions.promotion')),
            ],
            options={
                'db_table': 'promotion_categories',
                'unique_together': {('promotion', 'category')},
            },
        ),
        migrations.CreateModel(
            name='PromotionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='products.product')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='promotions.promotion')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productvariant')),
            ],
            options={
                'db_table': 'promotion_products',
                'unique_together': {('promotion', 'product')},
            },
        ),
    ]
