# Generated by Django 6.0.7 on 2026-08-09 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'footer_sections',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SEOSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=500)),
                ('og_title', models.CharField(blank=True, max_length=200)),
                ('og_description', models.TextField(blank=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/')),
                ('twitter_card', models.CharField(default='summary_large_image', max_length=50)),
                ('robots_txt', models.TextField(blank=True, default='User-agent: *\nAllow: /')),
                ('google_site_verification', models.CharField(blank=True, max_length=200)),
                ('canonical_url', models.URLField(blank=True)),
            ],
            options={
                'db_table': 'seo_settings',
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_name', models.CharField(default='PriyoShop', max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('phone_secondary', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('currency_code', models.CharField(default='BDT', max_length=10)),
                ('currency_symbol', models.CharField(default='৳', max_length=10)),
                ('timezone', models.CharField(default='Asia/Dhaka', max_length=50)),
                ('default_language', models.CharField(default='en', max_length=10)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(blank=True)),
                ('allow_registration', models.BooleanField(default=True)),
                ('allow_guest_checkout', models.BooleanField(default=True)),
                ('cod_enabled', models.BooleanField(default=True)),
                ('reviews_enabled', models.BooleanField(default=True)),
                ('wishlist_enabled', models.BooleanField(default=True)),
                ('account_discount_enabled', models.BooleanField(default=True)),
                ('min_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('require_email_at_checkout', models.BooleanField(default=False)),
                ('require_postal_code', models.BooleanField(default=False)),
                ('tax_enabled', models.BooleanField(default=False)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_label', models.CharField(default='VAT', max_length=50)),
            ],
            options={
                'db_table': 'site_settings',
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=300)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='settings_manager.footersection')),
            ],
            options={
                'db_table': 'footer_links',
                'ordering': ['sort_order'],
            },
        ),
    ]
