# Generated by Django 6.0.7 on 2026-08-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='account_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='announcement_bar_text',
            field=models.CharField(default='Special Eid Offer: Extra 2% Account Discount + Free Delivery in Dhaka!', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='dhaka_delivery_charge',
            field=models.DecimalField(decimal_places=2, default=60, max_digits=10),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='free_delivery_threshold',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=10),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_badge_text',
            field=models.CharField(default='Next-Gen Shopping Experience', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_btn_text',
            field=models.CharField(default='Explore Shop', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_btn_url',
            field=models.CharField(default='/shop', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_subtitle',
            field=models.TextField(default='Upgrade your lifestyle with authentic brand products, official warranty, extra 2% account discount & instant Cash on Delivery across Bangladesh.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_title',
            field=models.CharField(default='Next-Gen Smartphones & Modern Lifestyle', max_length=300),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='outside_dhaka_delivery_charge',
            field=models.DecimalField(decimal_places=2, default=120, max_digits=10),
        ),
    ]
