# Generated by Django 6.0.7 on 2026-08-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_manager', '0002_sitesetting_account_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='footer_color',
            field=models.CharField(choices=[('dark', 'Dark (Default)'), ('navy', 'Deep Navy Blue'), ('green', 'Dark Green'), ('purple', 'Deep Purple'), ('slate', 'Slate Gray'), ('brand', 'Brand Color')], default='dark', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_tagline',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
