# Generated by Django 6.0.7 on 2026-08-17 11:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightDeliveryTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. 0 - 1 kg', max_length=100)),
                ('min_weight_grams', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum weight in grams (inclusive)', max_digits=12)),
                ('max_weight_grams', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum weight in grams (inclusive), null for unlimited', max_digits=12, null=True)),
                ('charge', models.DecimalField(decimal_places=2, help_text='Delivery charge in BDT for this weight tier', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'shipping_weight_tiers',
                'ordering': ['sort_order', 'min_weight_grams'],
            },
        ),
    ]
