# Generated by Django 6.0.7 on 2026-08-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('promotions', '0002_dealoffercard'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deal_cards',
            field=models.ManyToManyField(blank=True, help_text='Tag this product to appear in specific Deals & Offers card pages', related_name='products', to='promotions.dealoffercard'),
        ),
    ]
