# Generated by Django 6.0.7 on 2026-08-17 11:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_add_deal_cards_m2m_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_charge_applicable',
            field=models.BooleanField(db_index=True, default=True, help_text='If false, this product weight is excluded from delivery charge calculation'),
        ),
        migrations.AddField(
            model_name='product',
            name='density_g_per_ml',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Density in g/ml (for volume products, e.g. Oil=0.92, Milk=1.03, Water=1.00)', max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='free_delivery_when_alone',
            field=models.BooleanField(db_index=True, default=False, help_text='If true, delivery is FREE (৳0) only when this is the sole product type in the order'),
        ),
        migrations.AddField(
            model_name='product',
            name='measurement_type',
            field=models.CharField(choices=[('weight', 'Weight'), ('volume', 'Volume')], default='weight', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='measurement_unit',
            field=models.CharField(choices=[('g', 'Gram (g)'), ('kg', 'Kilogram (kg)'), ('ml', 'Millilitre (ml)'), ('litre', 'Litre (L)')], default='g', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='measurement_value',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Weight in g/kg or Volume in ml/L', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='normalized_weight_grams',
            field=models.DecimalField(db_index=True, decimal_places=3, default=Decimal('0.000'), help_text='Automatically normalized weight in grams', max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Physical weight in kg', max_digits=8, null=True),
        ),
    ]
